In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with Dates

In [8]:
#converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract year

In [11]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
555 2019-08-15        3422       13       2       2019
613 2019-04-20        7430        1       2       2019
171 2019-01-25        4964        1      55       2019
587 2019-10-30        6153       22       6       2019
582 2019-07-22        1031        0       1       2019

2. Extract month

In [12]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

3. Month name

In [14]:
date['date_month_no'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month_no
0 2019-12-10        5628       25       3       2019      December
1 2018-08-15        3646       14     157       2018        August
2 2018-10-23        1859       25       1       2018       October
3 2019-08-17        7292       25       1       2019        August
4 2019-01-06        4344       25       3       2019       January

4. Extract days

In [16]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year date_month_no  date_day
0 2019-12-10        5628       25       3       2019      December        10
1 2018-08-15        3646       14     157       2018        August        15
2 2018-10-23        1859       25       1       2018       October        23
3 2019-08-17        7292       25       1       2019        August        17
4 2019-01-06        4344       25       3       2019       January         6

5. Day of week

In [17]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

6. Day of week - name

In [19]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id', 'city_id', 'orders']).head()

        date  date_year date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019      December        10         1       Tuesday
1 2018-08-15       2018        August        15         2     Wednesday
2 2018-10-23       2018       October        23         1       Tuesday
3 2019-08-17       2019        August        17         5      Saturday
4 2019-01-06       2019       January         6         6        Sunday

7. is weekend?

In [20]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

8. extract week of the year

In [26]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

9. Extract quarter

In [27]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

10. Extract semester

In [28]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 'H1', 'H2')
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,H2
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,H2
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,H2
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,H2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,H1

Time

extract time elapsed between dates

In [29]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 6, 6, 22, 58, 19, 492066)

In [30]:
today - date['date']

0     2370 days 22:58:19.492066
1     2852 days 22:58:19.492066
2     2783 days 22:58:19.492066
3     2485 days 22:58:19.492066
4     2708 days 22:58:19.492066
                 ...
995   2798 days 22:58:19.492066
996   2739 days 22:58:19.492066
997   2587 days 22:58:19.492066
998   2652 days 22:58:19.492066
999   2426 days 22:58:19.492066
Name: date, Length: 1000, dtype: timedelta64[ns]

In [31]:
(today - date['date']).dt.days

0      2370
1      2852
2      2783
3      2485
4      2708
       ...
995    2798
996    2739
997    2587
998    2652
999    2426
Name: date, Length: 1000, dtype: int64

Months passed

In [34]:
date['months_passed'] = np.round((today - date['date']).dt.days / 30.44, 0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,H2,78.0
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,H2,94.0
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,H2,91.0
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,H2,82.0
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,H1,89.0

In [35]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [36]:
#converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [37]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [38]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract time part

In [39]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time difference

In [40]:
today - time['date']

0     4556 days 22:08:19.492066
1     4420 days 23:18:19.492066
2     4906 days 22:37:19.492066
3     4208 days 22:27:19.492066
4     4605 days 23:47:19.492066
                 ...
995   5195 days 22:08:19.492066
996   4516 days 23:44:19.492066
997   4981 days 23:21:19.492066
998   5097 days 23:24:19.492066
999   4369 days 23:33:19.492066
Name: date, Length: 1000, dtype: timedelta64[ns]